### ISSUE TITLE
Compatability with NginxProxyManager

### ISSUE THREAD

**Issue by cdias-sil** [escopecz/docker-compose-mautic#6]
I've set-up a new instance of Mautic v5.2.1 with your docker compose along with a few changes for consistency with how we set-up our docker containers and compatibility with upgrading from production server is is running mariadb version 10.6.11.
After running 'docker compose up -d --build' and setting up the proxy in nginx proxy manager to forward to mautic-app:80 I can access mautic through http://domain.com but enabling SSL certificate through nignx proxy manager UI does not work.

If I leave **Force SSL** off I can continue to access through http://domain.com but not https://domain.com

This is my docker-compose.yml:
```
# Common volumes mappings between containers
x-mautic-volumes:
  &mautic-volumes
  - ./test/www/config:/var/www/html/config:z
  - ./test/www/logs:/var/www/html/var/logs:z
  - ./test/www/media/files:/var/www/html/docroot/media/files:z
  - ./test/www/media/images:/var/www/html/docroot/media/images:z
  - ./test/www/media/videos:/var/www/html/docroot/media/videos:z
  - ./test/cron:/opt/mautic/cron:z

services:
  mautic-db:
    container_name: mautic-db
    hostname: mautic-db
    image: mariadb:10.6.11
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - ./test/db:/var/lib/mysql
      - ./backups:/backups
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - mautic-net

  mautic-app:
    container_name: mautic-app
    hostname: mautic-app
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mautic-db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
    env_file:
      - .mautic_env
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      mautic-db:
        condition: service_healthy
    networks:
      - mautic-net
      - nginx-proxy

  mautic-cron:
    container_name: mautic-cron
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mautic-db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    env_file:
      - .mautic_env
    depends_on:
      mautic-app:
         condition: service_healthy
    networks:
      - mautic-net

  mautic-worker:
    container_name: mautic-worker
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mautic-db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    env_file:
      - .mautic_env
    depends_on:
      mautic-app:
        condition: service_healthy
    networks:
      - mautic-net
    deploy:
      replicas: 1

networks:
  nginx-proxy:
    external: true
  mautic-net:
    name: mautic-net
    driver: bridge
```

Dockerfile:
```
# Define the Mautic version as an argument
ARG MAUTIC_VERSION=5.2.1-apache

# Build stage:
FROM mautic/mautic:${MAUTIC_VERSION} AS build

# Install dependencies needed for Composer to run and rebuild assets:
RUN apt-get update && apt-get install -y git curl npm && rm -rf /var/lib/apt/lists/*

# Install Composer globally:
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install any Mautic theme or plugin using Composer:
RUN cd /var/www/html && \
    COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_PROCESS_TIMEOUT=10000  vendor/bin/composer require chimpino/theme-air:^1.0 --no-scripts --no-interaction

# Production stage:
FROM mautic/mautic:${MAUTIC_VERSION}

# Copy the built assets and the Mautic installation from the build stage:
COPY --from=build --chown=www-data:www-data /var/www/html /var/www/html
```

.env:
```
MYSQL_ROOT_PASSWORD=rootpassword
MYSQL_DATABASE=mautic
MYSQL_USER=user
MYSQL_PASSWORD=password
MYSQL_HOST=mautic-db
MYSQL_PORT=3306
DOCKER_MAUTIC_RUN_MIGRATIONS=true
DOCKER_MAUTIC_LOAD_TEST_DATA=false
```

.mautic_env:
```
MAUTIC_DB_HOST="${MYSQL_HOST}"
MAUTIC_DB_PORT="${MYSQL_PORT}"
MAUTIC_DB_DATABASE="${MYSQL_DATABASE}"
MAUTIC_DB_USER="${MYSQL_USER}"
MAUTIC_DB_PASSWORD="${MYSQL_PASSWORD}"
MAUTIC_MESSENGER_DSN_EMAIL="doctrine://default"
MAUTIC_MESSENGER_DSN_HIT="doctrine://default"
```
nginx proxy manager proxy configuration:

![Image](https://github.com/user-attachments/assets/b7c4a455-f3fe-4639-9999-52e83dfd8fda)

![Image](https://github.com/user-attachments/assets/04fe807c-1d0c-4c61-a7ba-a7bc80275376)

I've tried the following:
- Going to **Settings** => **Configuration** => **System Settings** => **Site Url** and changin this to https://domain.com. (Unable to connnect through http://domain.com after this)
- Going to '/var/www/html/config' and changing the site_url variable to https://domain.com. (Unable to connnect through http://domain.com after this)
- Going to **Settings** => **Configuration** => **System Settings** => **Miscellaneous Settings** and adding '0.0.0.0/0' to the “Trusted proxies” box.
- Going to **Settings** => **Configuration** => **System Settings** => **Additional Response Headers** and enabling:
  - **Strict Transport Security** to **Yes**
  - **Include Subdomains** to **Yes**
  - **Preload** to **Yes**
